---
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Remove "vim" package
    apt:
      name: vim
      state: absent

  - name: Install vim
    apt:
      name: vim
      state: present