---
- name: Remove the user 'pi'
  user:
    name: pi
    state: absent
    remove: yes

    
- name: Set authorized keys taken from url
  authorized_key:
    user: zero
    state: present
    key: https://github.com/Keita0805carp.keys
      
      
- name: set timezone to tokyo
  timezone:
    name: Asia/Tokyo
        
- name: Unconditionally reboot the machine with all defaults
  reboot:
    reboot_timeout: 100
    test_command: 'whoami'